modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${issue_tracker_url}"

[[mods]]
modId="${mod_id}"
version="${minecraft_version}-${mod_version}"
displayName="${mod_name}"
credits="Frustration at not being able to automate and get PMMO skills from Mekanism machines."
authors="${mod_authors}"
description="${mod_description}"
[[mods.modproperties]]
MixinConfigs="mixins.${mod_id}.json"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${loader_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mekanism"
mandatory=true
versionRange="[${mekanism_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="pmmo"
mandatory=true
versionRange="[${pmmo_version},)"
ordering="AFTER"
side="BOTH"