modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${issue_tracker_url}"

[[mods]]
modId="${mod_id}"
version="${minecraft_version}-${mod_version}"
displayName="${mod_name}"
logoFile="${mod_id}.png"
credits="Frustration at not being able to automate and get PMMO skills from Mekanism machines."
authors="${mod_authors}"
description="${mod_description}"

[[mixins]]
config="mixins.${mod_id}.json"

[[dependencies.${mod_id}]] #optional
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mekanism"
    type="required"
    versionRange="[${mekanism_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="pmmo"
    type="required"
    versionRange="[${pmmo_version},)"
    ordering="AFTER"
    side="BOTH"
